# Generated by Django 5.1.3 on 2024-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleWithVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('World', 'World'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
