# Generated by Django 5.1.3 on 2024-11-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articlewithvideo_alter_article_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleWithVideo',
        ),
    ]
